apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ac_fend
spec:
  rules:
  - host: asso-ciable.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ac_bend
            port:
              name: ac_bend