apiVersion: apps/v1
kind: Deployement
metadata:
  namespace: default
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  spec:
    volumes:
    - name: db-volume
      persistentVolumeClaim:
        claimName: postgres-pvc2
    containers:
    - name: db
      image: postgres:alpine
      ports:
        - containerPort: 5432